ARDMK_DIR=../../
DEPENDENCIES_FOLDER = ../../dependencies
DEPENDENCIES_MPIDE_DIR = $(DEPENDENCIES_FOLDER)/mpide-0023-linux64-20130817-test

ifeq ($(MPIDE_DIR),)
	MPIDE_DIR = $(DEPENDENCIES_MPIDE_DIR)
endif

DEPENDENCIES_ARDUINO_DIR = $(DEPENDENCIES_FOLDER)/arduino-1.0.5

ifeq ($(ARDUINO_DIR),)
	ARDUINO_DIR = $(DEPENDENCIES_ARDUINO_DIR)
endif
