ARDUINO_DIR = /Applications/Arduino.app/Contents/Resources/Java
PARSE_BOARD = ../../arduino-mk/ard-parse-boards

BOARD_TAG    = uno
ARDUINO_PORT = /dev/cu.usb*

ARDUINO_LIBS = 

include ../../arduino-mk/Arduino.mk
